### ISSUE TITLE
[Question] expectOutput(<regex>) ?

### ISSUE THREAD

**Issue by alegomes** [wolpl/clikt-testkit#1]
Hi there!

Is there a way to use `expectOutput()` with Regex instead of String?

tks

**Comment by alegomes** [comment]
Maybe, just replacing `shouldBe` by `shouldContain` or `shouldMatch` do the trick.

**Comment by wolpl** [comment]
Without changes to the library, you can check outputs with a regex by using the `expectOutput()` function without parameters and running assertions on its return value:
```kotlin
class TestCommand : CliktCommand() {
    override fun run() {
        echo("Hello World!")
    }
}

TestCommand().test {
    expectOutput() shouldMatch Regex("Hello [wW]orld!")
}
```

**Comment by alegomes** [comment]
Cool. Thanks!
